--- 
package:
  - dotnet-sdk-8.0
  - unzip
home_dir: /var/lib/nopCommerce
user: nop 
nop_zip_url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.70.5/nopCommerce_4.70.5_NoSource_linux_x64.zip
folders:
  - bin
  - logs
shell: /bin/bash
